# Generated by Django 4.2.30 on 2026-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('shopId', models.IntegerField()),
                ('creditImage', models.BinaryField(editable=True, null=True)),
                ('gameCash', models.FloatField(null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('getCredit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('userId', models.IntegerField()),
                ('client', models.TextField()),
                ('cash', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('userId', models.IntegerField()),
                ('retailId', models.IntegerField(null=True)),
                ('client', models.TextField()),
                ('cash', models.FloatField(null=True)),
                ('cashCredit', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('type', models.TextField()),
            ],
        ),
    ]
