# Generated by Django 4.2.13 on 2026-08-26 07:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clientType', models.TextField()),
                ('userId', models.IntegerField()),
                ('client', models.TextField()),
                ('type', models.TextField()),
                ('cash', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(django.db.models.expressions.RawSQL("EXTRACT(YEAR FROM (date AT TIME ZONE 'America/Guayaquil'))", []), name='idx_transaction_year'), models.Index(django.db.models.expressions.RawSQL("EXTRACT(MONTH FROM (date AT TIME ZONE 'America/Guayaquil'))", []), name='idx_transaction_month'), models.Index(django.db.models.expressions.RawSQL("((date AT TIME ZONE 'America/Guayaquil'))::date", []), name='idx_transaction_date')],
            },
        ),
    ]
